### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by toots** [sanette/tsdl-image#2]
Hi,

We're being hit by this issue on our alpine builds:
```
Fatal error: exception Dl.DL_error("Error loading shared library libSDL2_image-2.0.so: No such file or directory")
```

Looks like this should be fixed by a new release?

**Comment by sanette** [comment]
yes, this should be fixed by https://github.com/sanette/tsdl-image/commit/b376418ca18dc20959b6456dfd4f01e2bddbf9d9

I'll push this soon to `opam`.

Meanwhile you'd have to stick to version 0.2 (with name tsdl_image)

**Comment by sanette** [comment]
Version 0.3.1 with the fix is now in opam

**Comment by toots** [comment]
Awesome thanks you!!
