### ISSUE TITLE
Please remove startup log

### ISSUE THREAD

**Issue by smimram** [sanette/tsdl-image#8]
When using tsdl-image (and tsdl-ttf) in a program, we always get the following log messages at startup which is ennoying:
```
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
```
The [culprit is here](https://github.com/sanette/tsdl-image/blob/master/src/tsdl_image.ml#L45) and since it's a side effect of the module, I don't think that there is an easy way to disable it by changing the log levels before the log message is issued (I don't think that there is a reliable way of ordering the side effects of linked modules).

Unless I overlooked something, could you please remove this startup message in tsdl-image and tsdl-ttf? Thanks!

**Comment by sanette** [comment]
I think someone else already mentioned this. I'm ok to remove these logs, they have been added to help debugging when porting to other platforms, especially mac os.

**Comment by smimram** [comment]
Thanks! NB: I have actually been able to remove the logs for now by creating a new library which is liked before tsdl-image and raises the level of printed warnings: https://github.com/savonet/liquidsoap/pull/2913. However, I think that most people would rather have to do that.

**Comment by sanette** [comment]
done. But I haven't created a new opam version yet

**Comment by sanette** [comment]
now on opam!

**Comment by smimram** [comment]
Great, thanks!
